sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/bitcoind .
      - docker images
      - docker push $DOCKER_USERNAME/bitcoind
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/bitcoind echo "lets test the bitcoind cli here"
