---
- hosts: all
  become: yes

  tasks:
  - name: install docker system packages
    apt:
      name: docker.io
      state: present

  - name: install docker python dependencies
    pip:
      name: docker-py
      state: latest

  - name: run the container we just built
    docker_container:
        name: bitcoind
        image: azamatms/bitcoind
        state: started
