apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: bitcoind
spec:
  serviceName: bitcoind
  replicas: 1
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - bitcoind
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: bitcoind
          image: "azamatms/bitcoind"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: data
              mountPath: /root/.bitcoin
          ports:
            - containerPort: 8333
              name: full-node-port
            - containerPort: 8332
              name: alt-port
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: gp2
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
